export const SET_USER_CURRENCY = 'SET_USER_CURRENCY';
export const SET_EXCHANGE_INFO = 'SET_EXCHANGE_INFO';
export const SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES';
export const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
